services:
  backend:
    build:
      context: ./
      dockerfile: golang_server/Dockerfile
    image: marsbeaver/datingbackend
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=${JWT_KEY}
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - DATABASE=${DATABASE}

  frontend:
    build:
      context: ./
      dockerfile: flutter_frontend/Dockerfile
    image: marsbeaver/datingfrontend
    ports:
      - "80:80"
    environment:
      - BASE_URL=${BASE_URL}
