services:
  golang_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend 
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - JWT_KEY=${JWT_KEY}
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - DATABASE=${DATABASE}

  flutter_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE}
