version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: marsbeaver/datingbackend:v1
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=${JWT_KEY}
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - DATABASE=${DATABASE}

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    image: marsbeaver/datingfrontend:v1
    ports:
      - "80:80"
    environment:
      - BASE_URL=${BASE_URL}

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE}
